// Package httpshim makes ordinary `curl` and `wget` invocations in the agent's
// terminal go through the browser-fingerprinted HTTP stack, so a command the
// model reaches for out of habit still passes bot-detection.
//
// It works by placing small shim scripts named curl and wget on the shell's
// PATH. Each shim re-invokes the Antares binary as `antares _httpshim curl …`,
// which parses the common flags and performs the request with httpcloak. Any
// invocation the shim does not fully understand — an upload, a unix socket, a
// non-HTTP URL — is handed to the real curl/wget untouched, so nothing that
// worked before breaks.
package httpshim

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	"github.com/enowdev/antares/internal/config"
	"github.com/sardanioss/httpcloak"
)

// Tools are the commands the shim stands in for.
var Tools = []string{"curl", "wget"}

// Install writes the shim scripts and returns the directory to prepend to PATH.
// It is a no-op error on Windows, where the local shell is PowerShell and the
// PATH-shim trick does not apply cleanly.
func Install() (string, error) {
	if runtime.GOOS == "windows" {
		return "", fmt.Errorf("httpshim: not supported on windows")
	}
	self, err := os.Executable()
	if err != nil {
		return "", err
	}
	dir := filepath.Join(config.Home(), "shims")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	for _, tool := range Tools {
		script := "#!/bin/sh\n# Auto-generated by Antares — routes HTTP through the fingerprinted client.\nexec " +
			shellQuote(self) + " _httpshim " + tool + " \"$@\"\n"
		path := filepath.Join(dir, tool)
		// Rewrite only when the content changed, so the file's mtime stays put.
		if cur, err := os.ReadFile(path); err == nil && string(cur) == script {
			continue
		}
		if err := os.WriteFile(path, []byte(script), 0o755); err != nil {
			return "", err
		}
		_ = os.Chmod(path, 0o755)
	}
	return dir, nil
}

// Run dispatches an intercepted invocation. It is the entry point for the
// `antares _httpshim <tool> <args…>` subcommand and returns a process exit code.
func Run(tool string, args []string) int {
	switch tool {
	case "curl":
		return runCurl(args)
	case "wget":
		return runWget(args)
	default:
		return fallback(tool, args)
	}
}

// fallback runs the genuine tool with the original arguments, inheriting stdio,
// for anything the shim chooses not to handle.
func fallback(tool string, args []string) int {
	real := realBinary(tool)
	if real == "" {
		fmt.Fprintf(os.Stderr, "%s: command not found\n", tool)
		return 127
	}
	cmd := exec.Command(real, args...)
	cmd.Stdin, cmd.Stdout, cmd.Stderr = os.Stdin, os.Stdout, os.Stderr
	if err := cmd.Run(); err != nil {
		if ee, ok := err.(*exec.ExitError); ok {
			return ee.ExitCode()
		}
		fmt.Fprintf(os.Stderr, "%s: %v\n", tool, err)
		return 1
	}
	return 0
}

// realBinary finds the actual tool on PATH, skipping the shim directory so the
// fallback never re-invokes the shim.
func realBinary(tool string) string {
	shimDir := os.Getenv("ANTARES_SHIM_DIR")
	for _, dir := range filepath.SplitList(os.Getenv("PATH")) {
		if dir == "" || sameDir(dir, shimDir) {
			continue
		}
		p := filepath.Join(dir, tool)
		if info, err := os.Stat(p); err == nil && !info.IsDir() && info.Mode()&0o111 != 0 {
			return p
		}
	}
	return ""
}

func sameDir(a, b string) bool {
	if b == "" {
		return false
	}
	ap, err1 := filepath.Abs(a)
	bp, err2 := filepath.Abs(b)
	if err1 != nil || err2 != nil {
		return a == b
	}
	return filepath.Clean(ap) == filepath.Clean(bp)
}

// doRequest runs one request through the fingerprinted client using the preset
// and proxy the shell was configured with.
func doRequest(method, url string, headers map[string]string, body []byte, timeout time.Duration) (*httpcloak.Response, error) {
	preset := os.Getenv("ANTARES_HTTP_PRESET")
	if preset == "" {
		preset = "chrome-131"
	}
	var opts []httpcloak.Option
	if proxy := os.Getenv("ANTARES_HTTP_PROXY"); proxy != "" {
		opts = append(opts, httpcloak.WithProxy(proxy))
	}
	client := httpcloak.New(preset, opts...)
	defer client.Close()

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	// httpcloak v1.6+ takes multi-value headers and an io.Reader body.
	hdr := make(map[string][]string, len(headers))
	for k, v := range headers {
		hdr[k] = []string{v}
	}
	var bodyReader io.Reader
	if len(body) > 0 {
		bodyReader = bytes.NewReader(body)
	}
	return client.Do(ctx, &httpcloak.Request{
		Method:  method,
		URL:     url,
		Headers: hdr,
		Body:    bodyReader,
		Timeout: timeout,
	})
}

// isHTTPURL reports whether a token is an http(s) URL the shim can handle.
func isHTTPURL(s string) bool {
	return strings.HasPrefix(s, "http://") || strings.HasPrefix(s, "https://")
}

// shellQuote single-quotes a path for safe embedding in a /bin/sh script.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// statusLine renders a curl-style status line, e.g. "HTTP/2 200". The ALPN
// token httpcloak reports (h2, h3) is normalised to curl's spelling.
func statusLine(resp *httpcloak.Response) string {
	proto := strings.ToLower(strings.TrimSpace(resp.Protocol))
	switch proto {
	case "h2", "http/2":
		proto = "HTTP/2"
	case "h3", "http/3":
		proto = "HTTP/3"
	case "", "http/1.1", "http/1.0":
		if proto == "" {
			proto = "HTTP/1.1"
		} else {
			proto = strings.ToUpper(proto)
		}
	default:
		proto = strings.ToUpper(proto)
	}
	return fmt.Sprintf("%s %d", proto, resp.StatusCode)
}

// basename returns the last path segment of a URL, or a default, for tools that
// save to a file named after the URL. A host with no path (https://a.com/)
// yields the default rather than the host name.
func basename(rawurl, fallbackName string) string {
	u := rawurl
	if i := strings.IndexAny(u, "?#"); i >= 0 {
		u = u[:i]
	}
	if i := strings.Index(u, "://"); i >= 0 {
		u = u[i+3:]
	}
	slash := strings.Index(u, "/")
	if slash < 0 {
		return fallbackName // host only, no path
	}
	path := strings.TrimRight(u[slash+1:], "/")
	if i := strings.LastIndex(path, "/"); i >= 0 {
		path = path[i+1:]
	}
	if path == "" {
		return fallbackName
	}
	return path
}
